### ISSUE TITLE
#TB-7 아키텍쳐 세부 논의

### ISSUE THREAD

**Issue by handal95** [Team-Butler/go-calendar-practice#2]
협업 과정에서의 팀 프로젝트 아키텍쳐를 논의합니다.
 
## 1. File Tree Style 논의
**Domain Based Directory Structure**
```
├─cmd
├─config
└─pkg
    ├─db
    ├─loaders
    ├─middlewares
    └─modules
        ├─example
```

**Layer Based Directory Structure**
```
│  .gitignore
│  cmd.exe
│  go.mod
│  go.sum
│  [README.md](http://readme.md/)
│
├─cmd
│      entry.go
├─config
│      mysql.json
└─pkg
      ├─controllers
      │      example.go
      ├─db
      │      mysql.go
      ├─middlewares
      │      auth.go
      ├─models
      │      example.go
      ├─routers
      │      example.go
      │      router.go
      └─services
      │      example.go
```

## 2. 개발 정책 논의 

**Reference**
[팀버틀러 개발 정책 논의 문서](https://team-butler.atlassian.net/wiki/spaces/TB/pages/2064385)

[우아한 형제들 기술 블로그:우린 Git-flow를 사용하고 있어요](https://techblog.woowahan.com/2553/)

**Comment by Marades** [comment]
기존에 많이 쓰던 레이어 기반 구조 대신 도메인 기반 아키텍쳐를 사용하도록 합시다!
도메인 기반 구조로 작성해둔 코드는 오늘 오후에 집 가서 PR날리도록 하겠습니다
