### ISSUE TITLE
#TB-9 사용할 Database논의

### ISSUE THREAD

**Issue by Marades** [Team-Butler/go-calendar-practice#4]
RDBMS
- MySQL
- MariaDB
- Postgresql
...

NoSQL
- MongoDB
- AWS DynamoDB
...

저번에 Postgresql로 하는 걸로 얘기했던 거 같긴 한데 API명세를 할 때 다시 얘기해보면 좋을 거 같습니다

**Comment by handal95** [comment]
1. 우리 프로젝트의 초기 DB구축과정에서 NoSQL을 사용했을 때 장점이 크게 없을 것 같아요. 전반적으로 Event Log들이랑 내부 데이터들이 비정형적 요소가 많은 것도 아니고, 대체로 사용자 상호작용(TODO Check 등 )에 따라서 RW도 많이 발생할 것 같은데 RDBMS 계열이 어떨까요

+. 필요하다면(이후 사진이나 영상들을 다룰 일이 많아지는 등), 메인 DB를 RDBMS 계열에서 가져가고, NoSQL 계열에서 서브DB로 하던가 하는 방식은 어떨까요 ~~나-중에 일이 더 커질수도 있는건 비밀~~

**Comment by Marades** [comment]
그럼 PostgreSQL로 확정하고 이 이슈는 닫겠습니다~ :)
