### ISSUE TITLE
본 프로젝트 전 구현해볼 사항들 정의

### ISSUE THREAD

**Issue by Marades** [Team-Butler/go-calendar-practice#6]
본 프로젝트 때는 빠르게 API 작업을 들어가기 위해 외부 라이브러리나 서비스 등과 연동된 기능을 먼저 익혀보는 게 좋지 않을까 하는 생각이 들었습니다

그래서 저는 본 기능 들어가기 전에 Postgresql 연동 + Transaction 적용을 먼저 적용해볼까 합니다!

저번 스크럼 때
- Go Calendar API 연동 테스트
- CLI 구현
위 두가지를 진행하신다고 하셨는데 CLI는 구체적으로 어떤 것을 얘기하는 걸까요?

그리고 추가적으로 아래 두 가지도 논의되면 좋을 것 같습니다
1. ORM 사용 여부
2. Go 프로젝트에서 프로젝트 사전에 설정되어야하는 보안이나 기타 설정등이 추가로 존재하는지

**Comment by handal95** [comment]
1. CLI 구현은 그냥 아주 간단한 템플릿 정도 생각하고 있습니다.
 우선은 현재 Port 분리 등, 실행과 관련된 부분을 달아두려고 합니다.

2. ORM은 사용하는게 빠른 개발에 좋을 것 같긴 합니다. Python시절에 postgreSQL 쓸 때는
   sqlalchemy 썼는데, go에서는 써본적이 없지만 [GoLang SQLAlchemy](https://github.com/yunionio/sqlchemy)가 있긴하네요.
   스타가 29개라서, 다른 orm 있는지 더 찾아봐야할 것 같아요
    
3. 사전에 설정되어야 하는 보안과 기타 설정은 잘 모르겠네요. 같이 찾아보면 좋을 것 같아요.

**Comment by Marades** [comment]
ORM은 사전에 찾아보니까 gorm이 스타가 27800개 정도로 제일 유명한 거 같긴 합니다
다른 Go ORM 과 다르게 한국어 문서(https://gorm.io/ko_KR/)도 지원하는 걸로 보이네요
이걸로 진행해볼까요?? 한 번 봐주시고 의견 주세용

**Comment by handal95** [comment]
GORM이 좋을 것 같네요 :D

다만, 조사를 하다보면 일단은 입문용으로 활용을 하다가 갈아탈 필요가 있을 것 같아요.
가장 대중적인 GO ORM이기는 하지만, 기능상 불편한 점이 많은지 중간에 갈아타는 사람들이 많아보이네요.

gorm에서 다른 orm으로 변경하는 이유들은 
지원하는 Associations 기능이 불편한 문제, Join 기능 구현 문제 등 조금 불편한 이유들이 있어서 불만이 많은것 같아요.
일단은 PostgreSQL이라 큰 문제는 안되겠지만, Oracle Dialect 지원하지 않는 이슈도 있는 것 같구요.

별도로 GORM이랑 XORM 두개로 찾아보고 있었는데, 벤치마킹 관련 잘 정리된 글이 있어서 남깁니다 [xorm vs gorm benchmark](https://sumit-agarwal.medium.com/gorm-vs-xorm-part-1-d156ba9de404)
READ : GORM > XORM
WRITE : XORM > GORM

**Comment by Marades** [comment]
찾아보니 페이스북에서 만든 ent라는 라이브러리도 요새 인기가 좋은 거 같네용
장점으로는 struct tag없이 type으로 테이블이나 컬럼을 정의할 수 있고 다양한 메소드를 기본적으로 제공해 주는 거 같고 단점(?)으로는 Code First ORM이라는 점인 거 같네요

참고했던 링크 남깁니닷
https://github.com/ent/ent
https://umi0410.github.io/blog/golang/how-to-backend-in-go-db/

**Comment by handal95** [comment]
[Compare gorm vs ent](https://www.libhunt.com/compare-gorm-vs-ent)
이 문서에 두개의 비교와 하단에 비교할만한 orm들이 다 나와있긴 하네요.
Xorm
SQLBoiler - Generate a Go ORM tailored to your database schema.
go-pg - Golang ORM with focus on PostgreSQL features and performance
beego orm
gorp - Go Relational Persistence - an ORM-ish library for Go
xorm - xorm是一个简单而强大的Go语言ORM库，通过它可以使数据库操作非常简便。本库是基于原版xorm的定制增强版本，为xorm提供类似ibatis的配置文件及动态SQL支持，支持AcitveRecord操作
pgx - PostgreSQL driver and toolkit for Go
upper.io/db - Data access layer for PostgreSQL, CockroachDB, MySQL, SQLite and MongoDB with ORM-like features.
pop/soda - A Tasty Treat For All Your Database Needs
sqlc - Generate type-safe code from SQL
Squirrel - Fluent SQL generation for golang

추가로 ent관련 graphQL 관련글들도 가져와봤습니다.

[GraphQL의 개념 및 특징 (RESTful API 비교)](https://choseongho93.tistory.com/320)
[카카오 기술블로그 GraphQL](https://fe-developers.kakaoent.com/2022/220310-kakaopage-bff/)

**Comment by handal95** [comment]
GORM 기능이 불편한게 많다고 하지만, 입문용으로 적절하려나 싶었었는데,
어차피 언젠가 전환을 염두해둬야한다면 모르는 부분은 맞으면서 빨리 커보는것도 좋겠네용
일단 ent로 시도해보고, 영 아니다 싶으면 gorm으로 돌아오는것도 괜찮겠어여

DB:PostgreSQL 
ORM: ent
요 조합으로 한번 시도해봅시당
